### ISSUE TITLE
How do we make it work with s3-wagon-private?

### ISSUE THREAD

**Issue by coreagile** [xsc/lein-ancient#100]
Using `[lein-ancient "0.6.15"]`

I am getting the following error when running `lein ancient` (deploy works fine):
`(error) Assert failed: (not (empty? path))`

When reversing the following diff (sensitive information elided):
```diff --git a/project.clj b/project.clj
index 1c44e55..f54f305 100644
--- a/project.clj
+++ b/project.clj
@@ -37,9 +37,6 @@
-  :repositories [["private" {:url           "s3p://--elided--/"
-                             :no-auth       true
-                             :sign-releases false}]]
   :java-source-paths ["src/main/java" "src/test/java"]
   :source-paths ["src/main/clojure"]
   :test-paths ["src/test/clojure"]
@@ -51,6 +48,5 @@
                              [lein-bikeshed "0.5.1"]
                              [lein-dotenv "1.0.0"]
                              [lein-junit "1.1.8"]
-                             [lein-kibit "0.1.6"]
-                             [s3-wagon-private "1.3.1"]]
+                             [lein-kibit "0.1.6"]]
               :dependencies [[junit/junit "4.12"]]}})```

**Comment by eigenhombre** [comment]
A workaround is to change `"s3p://--elided--/"` to `"s3p://--elided--//"` (add extra trailing slash).

**Comment by eigenhombre** [comment]
Or, even more horribly:
`lein update-in : assoc :repositories '[["private" {:url "s3p://...elided...//" :no-auth true :sign-releases false}]]' -- ancient :all :no-colors`

**Comment by eigenhombre** [comment]
Or, even worse:
`lein update-in :repositories conj '["private" {:url "s3p://--elided--//" :no-auth true :sign-releases false}]]' -- ancient`

**Comment by xsc** [comment]
Hello! It has been a while, but recent changes to `ancient-clj` now allow usage of any Maven wagon for resolution. If you're still interested in this, could you verify the behaviour using `[lein-ancient "1.0.0-RC1"]`?

**Comment by tobiasadam0770** [comment]
I had the exact same problem as described in this issue and updating to `"1.0.0-RC1"` worked for me. Thanks a lot for providing a fix! 🥇 🎉 😀

**Comment by xsc** [comment]
@tobiasadam0770 Thanks for reporting back! I'll close the issue then.
