### ISSUE TITLE
Ability to prevent dependencies from updating -> LOCK

### ISSUE THREAD

**Issue by Freezystem** [xsc/lein-ancient#103]
I don't know if this feature already exists as its not documented.

It could be a nice feature to prevent some dependencies from upgrading so they will not appear in interactive mode for example. 

Maybe by adding a `:locked-dependencies` key to `project.clj` or something like that.

Regards!

**Comment by camdez** [comment]
Unless I misunderstand what you're looking for, this is already available (documented [here](https://github.com/xsc/lein-ancient#exclusionselection-of-artifacts)). Simply add `:upgrade false` to the dependency in your `:dependencies` list in `project.clj`.

e.g.

```clojure
{:dependencies [[foo "0.0.1" :upgrade false]])}
```

**Comment by Freezystem** [comment]
Perfect! It's totally what I meant. Sorry I missed it.
