### ISSUE TITLE
Regression tests should not be run if no tests configured

### ISSUE THREAD

**Issue by devurandom** [xsc/lein-ancient#47]
#11 and the associated commits add regression tests on upgrade, which is nice. However, Leiningen/Ancient also tries to run them if no tests are configured.

I suggest to just not try in this case, as otherwise one will run into this:
```
lein test user

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
Could not locate test command .
(error) tests have failed (use ':no-tests' to disable testing).
(error) #<ExceptionInfo clojure.lang.ExceptionInfo: Suppressed exit {:exit-code 1, :suppress-msg true}>
```

**Comment by xsc** [comment]
I feel like this is more of a problem with `lein cljsbuild test` (which causes the above output if I'm not mistaken): if there are no tests the command should not fail - just like `lein test´ itself.

In my opinion, running the tests by default is sane behaviour. Maybe we should add some global flag that disables it, though?

**Comment by devurandom** [comment]
Thanks for explaining this!
