### ISSUE TITLE
lein ancient does not use the mirror configured in ~/.lein/profiles.clj

### ISSUE THREAD

**Issue by ekimber** [xsc/lein-ancient#49]
I am using an organisation's internal mirror, configured in profiles.clj (it works much as described here: http://maven.apache.org/guides/mini/guide-mirror-settings.html)  However, ancient.clj is still trying to download artifacts from clojars.

**Comment by xsc** [comment]
@ekimber Thanks for reporting - I can verify the issue.

I seem to have expected that Leiningen automatically merges `:repositories` and `:mirrors` which is not the case, as far as I can tell. I'll have a look and fix it.

**Comment by xsc** [comment]
Can you try the latest SNAPSHOT?

```clojure
[lein-ancient "0.6.4-SNAPSHOT"]
```

**Comment by ekimber** [comment]
Great!  That snapshot build fixes the issue I was seeing.

**Comment by xsc** [comment]
Glad to hear. Released as

```clojure
[lein-ancient "0.6.4"]
```
