### ISSUE TITLE
Exclude specific dependencies from being upgraded

### ISSUE THREAD

**Issue by henriklundahl** [xsc/lein-ancient#51]
Make it possible to exclude specific dependencies from being upgraded.

**Comment by xsc** [comment]
I'm not sure about this one. Where would you specify those dependencies? It'd probably have to be somewhere globally since lein-ancient is usually not included as a project-specific plugin - and does that make sense? Different projects might want to exclude different dependencies...

So, did you have a specific mechanism in mind?

**Comment by henriklundahl** [comment]
My first thought was at the command line, but that would be quite clumsy.

Better would be to have an :ancient key in project.clj. The value could be a map with a :exclusions or :upgrade-exclusions key. Also other configuration like the :allow-qualified, :check-clojure and :no-tests could possibly be specified here.

Thanks for this very useful plugin, by the way.  :-)

**Comment by bendlas** [comment]
I have a practical use case for such an exclusion mechanism:

[webnf](https://github.com/webnf/webnf/blob/master/project.clj) is a general purpose module/dependency collection, which I maintain with the help of [lein-modules](https://github.com/jcrossley3/lein-modules). This allows to centrally specify the version of common dependencies (or overrides), and use `"_"` as the dependency version in modules.

Currently `lein-ancient` sees `"_"` as an outdated dependency in the module, which prevents me from running `lein modules ancient upgrade`.
It would be very convenient for me, if I could specify an exclusion (or have `lein-ancient` ignore `"_"` versions by default).

**Comment by xsc** [comment]
I have a suggestion - how about allowing a `:upgrade?` key directly in the dependency vector?

```clojure
(defproject test-project "0.1.0-SNAPSHOT"
  :dependencies [[artifact "0.1.0"]
                 [artifact2 "0.1.0" :upgrade? false]])
```

As far as I can see, Leiningen does not complain and this would keep the information directly where it belongs.

**Comment by rsslldnphy** [comment]
Would this proposed solution also work for simply checking dependencies rather than upgrading them? I'd like to add `lein ancient` to our travis builds and have them fail if there are any out of date packages, but for some libraries we actually need the non-latest version, so would like to add these as exclusions.

**Comment by xsc** [comment]
You can try the current snapshot (`0.6.8-SNAPSHOT`) - it should already behave exactly like you describe.

**Comment by rsslldnphy** [comment]
Ace, thank you @xsc!

**Comment by henriklundahl** [comment]
I somehow missed the comment with the suggestion. I think this will be fine. Thanks!

**Comment by shmish111** [comment]
I just came across this.  I want to use lein-ancient to check public dependencies but I also want to use it separately to automatically upgrade our private dependencies.  Upgrading public ones needs to be done manually so we would only use check, private deps will be done by jenkins.  If this `:upgrade? false` mechanism is used, will `lein ancient check` still show the old deps?

**Comment by shmish111** [comment]
Also, I've realised what would be really useful is to only upgrade SNAPSHOT dependencies, can I open a new issue for this?  Does it make sense?

**Comment by xsc** [comment]
@shmish111 Good point! Maybe `:upgrade?` should not be a boolean value and rather a keyword/string (or seq?) representing partitions of dependencies, e.g.:

```clojure
:dependencies [[internal/x "0.1.0" :upgrade :private]
               [cheshire "0.1.0"]]
```

Then we could add command line options like `:only` or `:except` where you pass those values, e.g.:

```
$ lein ancient check :only private :except snapshot
```

Thoughts?

(Also, having `false` as a value there should still prevent checks/upgrades, I guess. And SNAPSHOTs might be implicitly tagged with `:snapshot`, to address your second idea.)

**Comment by shmish111** [comment]
That would be awesome.

**Comment by xsc** [comment]
This is released in:

```clojure
[lein-ancient "0.6.8"]
```

You can now specify `:upgrade false` in the artifact vector to exclude an artifact, as well as e.g. `:upgrade :crypto` and `lein ancient :only crypto` for selective checks/upgrades.

**Comment by henriklundahl** [comment]
Great, thanks!
