### ISSUE TITLE
v6.5+: java.lang.Exception: response content-type is not XML

### ISSUE THREAD

**Issue by ptaoussanis** [xsc/lein-ancient#52]
Hi Yannick,

I'm running into a problem with lein-ancient 6.5+ (6.5 and 6.6). Running `lein ancient :all` at the command line produces:

```
(warn)  [central] - Δ 2112ms - failure when checking com.cemerick/clojurescript.test: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [central] - Δ 2115ms - failure when checking org.clojure/tools.reader: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2364ms - failure when checking lein-autoexpect/lein-autoexpect: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2377ms - failure when checking lein-expectations/lein-expectations: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2382ms - failure when checking com.cemerick/clojurescript.test: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2412ms - failure when checking lein-pprint/lein-pprint: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2436ms - failure when checking lein-ancient/lein-ancient: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 2447ms - failure when checking codox/codox: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [sonatype-oss-public] - Δ 2571ms - failure when checking com.cemerick/clojurescript.test: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [sonatype-oss-public] - Δ 2631ms - failure when checking org.clojure/tools.reader: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 1584ms - failure when checking expectations/expectations: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
(warn)  [clojars] - Δ 1586ms - failure when checking com.cemerick/double-check: java.lang.Exception: response content-type is not XML (#{"text/xml" "application/xml"}): null
all artifacts are up-to-date.
```

This happens reliably on my end, so a little surprised no one else has reported this yet? Any ideas?

Thanks a lot! Cheers :-)

**Comment by xsc** [comment]
Hi Peter,

do you have any `:mirrors` set up? Or are you behind a proxy?

Maybe it's some dependency conflict in the plugins - could you do `lein deps :plugin-tree` and paste the output?

Thanks!
Yannick

**Comment by ptaoussanis** [comment]
Hi Yannick,

> do you have any :mirrors set up?

Not as far as I'm aware (not intentionally); how would I confirm?

> Or are you behind a proxy?

No proxy. And have tried a few different connections with the same results: WiFi, 3G, landline - all different providers.

> Maybe it's some dependency conflict in the plugins - could you do lein deps :plugin-tree and paste the output?

[encore](https://github.com/ptaoussanis/encore)'s output is:
```
(Possibly confusing dependencies found:)
([com.cemerick/clojurescript.test "0.3.3"] -> [org.clojure/clojurescript "0.0-2411"])
( overrides)
([com.keminglabs/cljx "0.6.0"] -> [com.cemerick/piggieback "0.1.5"] -> [org.clojure/clojurescript "0.0-2665"])
(
Consider using these exclusions:)
([com.keminglabs/cljx "0.6.0" :exclusions [org.clojure/clojurescript]])
nil
 [codox "0.8.11"]
   [codox/codox.leiningen "0.8.11"]
 [com.cemerick/clojurescript.test "0.3.3"]
   [org.clojure/clojure "1.6.0"]
   [org.clojure/clojurescript "0.0-2411"]
     [com.google.javascript/closure-compiler "v20140625"]
       [args4j "2.0.26"]
       [com.google.code.findbugs/jsr305 "1.3.9"]
       [com.google.guava/guava "17.0"]
       [com.google.javascript/closure-compiler-externs "v20140625"]
       [com.google.protobuf/protobuf-java "2.5.0"]
       [org.json/json "20090211"]
     [org.clojure/data.json "0.2.3"]
     [org.clojure/google-closure-library "0.0-20140718-946a7d39"]
       [org.clojure/google-closure-library-third-party "0.0-20140718-946a7d39"]
     [org.mozilla/rhino "1.7R4"]
 [com.keminglabs/cljx "0.6.0"]
   [com.cemerick/piggieback "0.1.5"]
   [net.cgrand/sjacket "0.1.1" :exclusions [[org.clojure/clojure]]]
     [net.cgrand/parsley "0.9.2"]
     [net.cgrand/regex "1.1.0"]
   [org.clojure/core.match "0.2.0"]
   [watchtower "0.1.1"]
 [lein-ancient "0.6.4"]
   [ancient-clj "0.3.1"]
     [clj-aws-s3 "0.3.10" :exclusions [[joda-time] [org.clojure/clojure]]]
       [com.amazonaws/aws-java-sdk "1.7.5"]
         [com.fasterxml.jackson.core/jackson-annotations "2.1.1"]
         [com.fasterxml.jackson.core/jackson-core "2.1.1"]
         [com.fasterxml.jackson.core/jackson-databind "2.1.1"]
         [org.apache.httpcomponents/httpclient "4.2"]
           [org.apache.httpcomponents/httpcore "4.2"]
     [clj-time "0.9.0" :exclusions [[joda-time] [org.clojure/clojure]]]
     [commons-codec "1.10" :exclusions [[joda-time] [org.clojure/clojure]]]
     [commons-logging "1.2" :exclusions [[joda-time] [org.clojure/clojure]]]
     [http-kit "2.1.19" :exclusions [[joda-time] [org.clojure/clojure]]]
     [joda-time "2.7" :exclusions [[joda-time] [org.clojure/clojure]]]
     [org.clojure/data.xml "0.0.8" :exclusions [[joda-time] [org.clojure/clojure]]]
   [commons-io "2.4"]
   [jansi-clj "0.1.0"]
     [org.fusesource.jansi/jansi "1.11"]
   [potemkin "0.3.11"]
     [clj-tuple "0.1.7"]
     [riddley "0.1.7"]
   [rewrite-clj "0.4.12"]
     [org.clojure/tools.reader "0.8.13" :exclusions [[org.clojure/clojure]]]
   [version-clj "0.1.2"]
 [lein-autoexpect "1.4.2"]
   [jakemcc/clojure-gntp "0.1.1" :exclusions [[org.clojure/clojure]]]
   [leinjacker "0.4.2" :exclusions [[org.clojure/clojure]]]
     [org.clojure/core.contracts "0.0.1"]
       [org.clojure/core.unify "0.5.3"]
   [org.clojure/tools.namespace "0.2.8" :exclusions [[org.clojure/clojure]]]
 [lein-cljsbuild "1.0.5"]
   [fs "1.1.2"]
     [org.apache.commons/commons-compress "1.3"]
   [lein-cljsbuild/cljs-compat "1.0.0-20150219.215334-32"]
 [lein-expectations "0.0.8"]
   [expectations "1.4.5"]
 [lein-pprint "1.1.2"]
```

Note that I get the same results with every project, even if I pull out all plugin dependencies besides `lein-ancient`. I.e. doesn't look like a dep conflict to me.

Just let me know if any other details would be handy.

Cheers :-)

**Comment by xsc** [comment]
Hi Peter,

> how would I confirm?

If neither your `profiles.clj` nor your `project.clj` contain the `:mirrors` key, none should be used. I assume that you'd have seen that key if it were used anywhere.

> I.e. doesn't look like a dep conflict to me.

Maybe with Leiningen's own dependencies? Which version (of Leiningen) are your using?

Cheers! :)

---

__More thoughts:__

The major change between 0.6.4 and 0.6.5+ is switching from `http-kit`'s client to `clj-http` which should be the reason for what you're observing. - but it's more than curious that there seems to be nobody else with that issue...

Also, I don't think I'm trying to read the `content-type` header using the wrong key since clj-http's README explicitly states:

> Response headers can be read as keywords or strings of any case. If the server responds with a “Date” header, you could access the value of that header as :date, “date”, “Date”, etc.

**Comment by ptaoussanis** [comment]
> If neither your profiles.clj nor your project.clj contain the :mirrors key, none should be used. I assume that you'd have seen that key if it were used anywhere.

Okay, definitely no mirrors then.

> Maybe with Leiningen's own dependencies? Which version (of Leiningen) are your using?

That's it, you found the problem: **Lein 2.4.2 consistently produces the error, 2.5.1 works fine**.

I'm avoiding the latest Lein releases lately due to some unresolved bugs with them, so I'll just hold back on `lein-ancient` releases for a while.

> switching from http-kit's client to clj-http

May I ask what your motivation for the change was? Just curious.


Thanks again for your help with this! Feel free to close the issue if you'd like.

Cheers :-)

**Comment by xsc** [comment]
> May I ask what your motivation for the change was?

There was an issue (#50) using http-kit's client and a proxy. Apparently, http-kit does neither use the system's proxy settings nor allow for manual specification of one.

Anyways, could you try the latest SNAPSHOT?

```clojure
[lein-ancient "0.6.7-SNAPSHOT"]
```

I think I managed to get the plugin compatible with Leiningen >= 2.4.0 again.

**Comment by ptaoussanis** [comment]
> Anyways, could you try the latest SNAPSHOT?

Snapshot is working with lein 2.4.2

**Comment by xsc** [comment]
[Release Notes](https://github.com/xsc/lein-ancient/releases/tag/clojars-0.6.7)

**Comment by ptaoussanis** [comment]
Thanks Yannick, much appreciated! Cheers :-)

**Comment by cch1** [comment]
We ran into this problem after an older s3 wagon polluted our company repo with artifacts with the wrong content type.  Beware.
