### ISSUE TITLE
subtask help strings for "get" and "latest" should differ

### ISSUE THREAD

**Issue by uvtc** [xsc/lein-ancient#53]
Output from `lein help ancient` says:

~~~
Subtasks available:
check                Check projects for outdated artifacts. (default)
profiles             Check profiles for outdated artifacts.
get                  List all versions for a given artifact.
latest               List all versions for a given artifact.
upgrade              Upgrade all project artifacts.
upgrade-profiles     Upgrade all artifacts in the global and local profiles.
~~~

The help lines for the "get" and "latest" subtasks are identical, which I think is incorrect.

Also, maybe the one for `get` should mention "human-readable", whereas the one for `latest` might note, "suitable for inclusion in project.clj" or similar.

**Comment by xsc** [comment]
Thanks for noticing! It would now read as follows:

```
Subtasks available:
check                Check projects for outdated artifacts. (default)
profiles             Check profiles for outdated artifacts.
get                  List all versions for a given artifact.
latest               Print a version vector for the given artifact's latest release.
upgrade              Upgrade all project artifacts.
upgrade-profiles     Upgrade all artifacts in the global and local profiles.
```

What do you think?

**Comment by uvtc** [comment]
The new subtask description looks good.

As an aside, the subtask names throw me a bit (except the last one). "get" makes it sound like the subtask is going to get (fetch, download) the artifacts (which, I realize, makes no sense). As far as I understand, lein-ancient does essentially three things: it checks, shows, and upgrades. So, I think the subtask names would be more consistent as:

    check-project
    check-profiles
    show-versions <artifact>
    show-latest   <artifact>
    upgrade-project
    upgrade-profiles
