### ISSUE TITLE
Make subtask names more consistent

### ISSUE THREAD

**Issue by uvtc** [xsc/lein-ancient#54]
The subtask names throw me a bit (except the last one).

    check
    profiles
    get
    latest
    upgrade
    upgrade-profiles

For one thing, "get" makes it sound like the subtask is going to get (fetch, download) the artifacts (which, I realize, makes no sense).

As far as I understand, lein-ancient does essentially three things: it checks, shows, and upgrades. So, I think the subtask names would be more consistent as:

    check-project
    check-profiles
    show-versions <artifact>
    show-latest   <artifact>
    upgrade-project
    upgrade-profiles

**Comment by xsc** [comment]
I agree with `check-profiles`, `show-versions` and `show-latest` - `check` (which isn't used explicitly anyways, I'm assuming) and `upgrade` don't seem that confusing to me. Of course, I have to maintain backwards compatibility, so these would be some gradual changes over the next few versions.

**Comment by uvtc** [comment]
Sounds good.

**Comment by uvtc** [comment]
Nice. Thanks!

**Comment by xsc** [comment]
@uvtc Yeah, sorry for the delay!
