### ISSUE TITLE
New warning with Leiningen 2.5.2

### ISSUE THREAD

**Issue by brunchboy** [xsc/lein-ancient#58]
Since upgrading Leiningen to 2.5.2, running `lein ancient` gives me the following:

```
lein ancient
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
all artifacts are up-to-date.
```

**Comment by conan** [comment]
Yeah I see this too.

**Comment by gigafone** [comment]
+1

**Comment by xsc** [comment]
Just for clarification, in case the link to technomancy/leiningen#1959 wasn't enough: this problem comes from a conflict between Clojure 1.7.0 / clj-http 0.9.2 (which both are pinned dependencies in Leiningen) and has to be fixed in Leiningen itself.

**Comment by brunchboy** [comment]
Thanks, @xsc, that was how I interpreted the link, but I figured it would make sense to leave this issue open so people can see that fact, rather than opening a series of new issues until Leiningen gets fixed.

**Comment by xsc** [comment]
Sure, and I completely agree - I just tried to direct the `+1`s towards Leiningen. ;)

**Comment by gigafone** [comment]
/me just did a +1 over at https://github.com/technomancy/leiningen/issues/1959

**Comment by jasonjckn** [comment]
+1

**Comment by xsc** [comment]
Leiningen 2.6.0 has been released, including a bump to clj-http which should get rid of that warning.

**Comment by brunchboy** [comment]
Great, thanks! I’ve just pushed an update to Homebrew so their users will be getting this version soon.
