### ISSUE TITLE
Support S3-wagon-private

### ISSUE THREAD

**Issue by danielcompton** [xsc/lein-ancient#64]
When running `lein ancient` 0.6.0 or higher in a project that is using [S3-wagon-private](https://github.com/technomancy/s3-wagon-private), I get the following errors:

```
$lein ancient
(warn)  [releases] - Δ  936ms - failure when checking org.clojure/clojurescript: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  939ms - failure when checking org.clojure/clojurescript: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  937ms - failure when checking com.andrewmcveigh/cljs-time: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  943ms - failure when checking com.cognitect/transit-cljs: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  938ms - failure when checking com.cemerick/clojurescript.test: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  937ms - failure when checking clj-stacktrace/clj-stacktrace: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  944ms - failure when checking binaryage/devtools: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  943ms - failure when checking clj-stacktrace/clj-stacktrace: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  944ms - failure when checking binaryage/devtools: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  942ms - failure when checking prismatic/schema: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  946ms - failure when checking com.cognitect/transit-cljs: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  943ms - failure when checking com.andrewmcveigh/cljs-time: java.lang.Exception: [status=403] AccessDenied
(warn)  [releases] - Δ  945ms - failure when checking prismatic/schema: java.lang.Exception: [status=403] AccessDenied
(warn)  [snapshots] - Δ  951ms - failure when checking com.cemerick/clojurescript.test: java.lang.Exception: [status=403] AccessDenied
[org.clojure/clojurescript "1.7.122"] is available but we use "1.7.58"
[com.andrewmcveigh/cljs-time "0.3.13"] is available but we use "0.3.11"
[prismatic/schema "1.0.1"] is available but we use "0.4.4"
```

It looks like it is trying to access the repo with bad authentication credentials. The S3 wagon needs `:username` and `:passphrase`, not `:password` like you might expect. My suspicion is that lein-ancient is trying to use `:password`, and auth is failing. I tried debugging this, but wasn't able to get too far. If you're able to give me some pointers, I can investigate this further.

Thanks!

**Comment by xsc** [comment]
lein-ancient uses [ancient-clj](https://github.com/xsc/ancient-clj) for retrieving available versions, and that should handle `:username`/`:passphrase` and `:username`/`:password` correctly. So, debugging should probably start at:

```clojure
(require '[ancient-clj.core :as anc])
(anc/versions-per-repository!
  'some-artifact
  {:repositories {"private-s3" {:uri "s3p://bucket/path/to/your/repo"
                                :username "S3_ACCESS_KEY"
                                :passphrase "S3_SECRET_KEY"}}})
```

Since it didn't say `InvalidAccessKeyId` or `SignatureDoesNotMatch`, I'm inclined to believe that the credentials are passed correctly. So, maybe an issue with ancient-clj's S3 client connecting to the wrong region, or bucket permissions?

**Comment by xsc** [comment]
Any news on this?

**Comment by danielcompton** [comment]
Sorry, I've been on paternity leave, will checkin when I'm back on board :)

**Comment by xsc** [comment]
Closing for now, feel free to reopen once there is more information.

**Comment by timgilbert** [comment]
Just as a note, using the s3-wagon-private alternative [lein-essthree](https://github.com/dparis/lein-essthree) in a project causes `lein ancient` to fail out with an error:

```
(error) Assert failed: (string? username)
```

It would be nice if `lein ancient` had an option to only check maven-central and clojars so it could just skip over my private repositories (personally, I mainly use it to check for updates to open-source stuff).

**Comment by danielcompton** [comment]
Just an update on this, with s3-wagon-private, it seems like this is now working fine with lein-ancient  0.6.10. Thanks!

**Comment by xsc** [comment]
@danielcompton Thanks for the update!

@timgilbert You could use the [dependency marker mechanism](https://github.com/xsc/lein-ancient#exclusionselection-of-artifacts) to exclude dependencies from automatic upgrades:

```clojure
:dependencies [[potemkin "0.4.3"]
               [private/artifact "0.1.0" :upgrade false]
               ...]
```

Or with an actual marker:

```clojure
:dependencies [[potemkin "0.4.3"]
               [private/artifact "0.1.0" :upgrade :private]
               ...]
```

Then you can use `:only` and `:exclude` to configure checking/upgrade, e.g.:

```
$ lein ancient :exclude private
```

Of course, this needs introduction of lein-ancient-specific stuff into your `project.clj` – so if that's a no-go feel free to open an issue for a repository-selection feature. :)

**Comment by rberger** [comment]
Looks like this is a problem again, now that s3-wagon-private >= 1.3.0 supports the AWS profiles. So no longer does s3-wagon-private require the setting of AWS Credentials in the profile.clj. It now properly  uses the ~/.aws/credentials.

Not having credentials in the profile.clj seems to break lein ancient. I get the dreaded
```
(error) Assert failed: (string? username)
```

Any chance lein ancient could support the aws sdk standard of getting creds from ~/.aws/credentials? It should "just work" if its using a standard AWS SDK. Though I see that the `aws-java-sdk-s3` is pinned to "1.9.0" in the project.clj. This version is from Oct, 2014. The current version is 1.11.123. Does it really still need to be pinned?

Thanks!

**Comment by xsc** [comment]
The main problem here is that [clj-aws-s3](https://github.com/weavejester/clj-aws-s3) requires a map of username/password/region as input to every S3 function. Now, that library is deprecated anyways, so switching to something else makes a lot of sense, in the course of which we could also get configuration right.

Possible candidates could be [amazonica][amazonica] and [clj-s3-client][clj-s3], both of which seem to take the correct S3 credentials.

[amazonica]: https://github.com/mcohen01/amazonica#s3
[cljs-s3]: https://github.com/adtile/clj-s3-client

I'll take a look!

**Comment by sattvik** [comment]
I have submitted https://github.com/xsc/ancient-clj/pull/8 which should be able to fully support s3-wagon-private.  If you would like to try it out, I have pushed `io.sattvik/lein-ancient 0.6.11` to Clojars.  It seems to work for me.

**Comment by joekiller** [comment]
`io.sattvik/lein-ancient 0.6.11` fixed the `(error) Assert failed: (string? username)` problem for me.

**Comment by xsc** [comment]
__[Release 0.6.12](https://github.com/xsc/lein-ancient/releases/tag/clojars-0.6.12)__
