### ISSUE TITLE
lein-ancient doesn't handle alpha releases

### ISSUE THREAD

**Issue by ChrisPickard** [xsc/lein-ancient#65]
I have a dependencies vector that looks like
`  :dependencies [[org.clojure/clojure "1.7.0-alpha1"]
                 [org.clojure/clojurescript "0.0-2311"]
                 [org.clojure/core.async "0.1.338.0-5c5012-alpha"]]
`

and while it upgrades the clojurescript vector correctly, it doesn't upgrade the clojure vector to the stable version

**Comment by xsc** [comment]
It's not that lein-ancient doesn't handle alpha releases, but that it ignores the Clojure (and soon ClojureScript - feel free to weigh in at #63) artifact by default. You can have it checked by adding the `:check-clojure` flag to the command line.
