### ISSUE TITLE
lein-ancient 0.6.8-SNAPSHOT doesn't play well with lein do, AKA find dependencies and plugins at the same time

### ISSUE THREAD

**Issue by belucid** [xsc/lein-ancient#66]
This is great:

```console
lein ancient
```

And this is too:

```console
lein ancient :plugins
```

But what I'd really like is 1 command that will find out of date dependencies and plugins. It's unfortunate that you can't do both with 1 command (as far as I can tell), and maybe you should be able to. So that's one issue.

A separate but somewhat related issue, is that it seems our possible work around, `lein do`, doesn't work with lein-ancient 0.6.8-SNAPSHOT.

This works as expected, both these tasks run:

```console
lein do version, ancient
Leiningen 2.5.3 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
[midje "1.7.0"] is available but we use "1.6.0"
[ring-mock "0.1.5"] is available but we use "0.1.3"
```

And on lein-ancient 0.6.7, this works fine too:

```console
lein do ancient, version
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
[midje "1.7.0"] is available but we use "1.6.0"
[ring-mock "0.1.5"] is available but we use "0.1.3"
Leiningen 2.5.3 on Java 1.8.0_60 Java HotSpot(TM) 64-Bit Server VM
```

But on 0.6.8-SNAPSHOT, the 2nd task, `version`, never runs:

```console
lein do ancient, version
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
[aprint "0.1.3"] is available but we use "0.1.0"
[midje "1.7.0"] is available but we use "1.6.0"
[ring-mock "0.1.5"] is available but we use "0.1.3"
```

The downside of this regression, in particular, is it makes this work around on 0.6.7:

```console
lein do ancient, ancient :plugins
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
[midje "1.7.0"] is available but we use "1.6.0"
[ring-mock "0.1.5"] is available but we use "0.1.3"
[lein-ring "0.9.6"] is available but we use "0.9.5"
[lein-cljsbuild "1.1.0"] is available but we use "1.0.0"
```

No longer work on 0.6.8:

```console
lein do ancient, ancient :plugins
WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update
[aprint "0.1.3"] is available but we use "0.1.0"
[midje "1.7.0"] is available but we use "1.6.0"
[ring-mock "0.1.5"] is available but we use "0.1.3"
```

**Comment by belucid** [comment]
FWIW, if I put it in an alias, it seems to work OK.

Such as:

```clojure
:aliases {
    "ancient!" ["do" "ancient" ":allow-qualified," "version"] 
}

So... that seems odd.

or

```clojure
:aliases {
    "ancient!" ["do" "ancient" ":allow-qualified," "ancient" ":plugins" ":allow-qualified"] 
}

**Comment by xsc** [comment]
Regarding checks on all the things (see `lein help ancient check` & co.):

```
lein ancient :all
```

Regarding the problems with `lein do`, I thinks this is a side-effect of #55 - lein-ancient produces a non-zero error code when it finds outdated stuff, probably prompting `lein do` to abort. (I feel that might actually be useful behaviour, since it allows calls that only run if dependencies are up-to-date. Probably a matter of taste.)

**Comment by belucid** [comment]
Y... I can see why you might want the non-zero error code. That makes sense.

Thanks for `:all`. Didn't notice that was an option.
