### ISSUE TITLE
ancient looks for higher versions, not more recent deploys

### ISSUE THREAD

**Issue by ccfontes** [xsc/lein-ancient#68]
`lein-ancient` looks for higher versions of jars specified in `project.clj`. I think maybe it should look for more recent deploys instead. The following example ilustrates my reasoning:

```
> lein ancient
[twitter-api "1.0.0"] is available but we use "0.7.8"
```
Version `1.0.0` is actually much older than `0.7.8`. Probably this was due to some mistake, but mistakes do happen, and can't be easily erased in the case of clojars.

**Comment by xsc** [comment]
@ccfontes Thanks for the report but changing this behaviour will break handling of other artifacts (e.g. those that push `1.x` patches while there already is a `2.x` line of releases).

For now, I'd (grudgingly) advise on using `:upgrade? false´ in the artifact vector to get rid of the warning - in the long run functionality could be added to only upgrade minor/patch numbers if desired.
