### ISSUE TITLE
Cannot create loader from scp

### ISSUE THREAD

**Issue by aiba** [xsc/lein-ancient#71]
I use an "scp://..." repository as described in https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#scp

Using lein ancient with this, yields an error:

```
(error) cannot create loader from: {:uri "scp://...", :ancient-clj.io/scheme :scp}
```

Can we change this to a warning so lein anceint still basically runs (and maybe skips the scp repos)?  As is, I need to comment out this line in project.clj before running ancient.

**Comment by xsc** [comment]
Good point, this is not the most user-friendly behaviour. Can you try the SNAPSHOT?

```clojure
[lein-ancient "0.6.9"]
```

If the behaviour is now okay for you I'll cut a release. :)

**Comment by aiba** [comment]
Beautiful, working great with `0.6.9-SNAPSHOT`.  I like the warning rather than fatal error.  Thank you!

**Comment by xsc** [comment]
Released as:

```clojure
[lein-ancient "0.6.9"]
```

[Release Notes](https://github.com/xsc/lein-ancient/releases/tag/clojars-0.6.9)
