### ISSUE TITLE
Add support for :managed-dependencies

### ISSUE THREAD

**Issue by henriklundahl** [xsc/lein-ancient#76]
Leiningen 2.7.0 was just released and it includes support for adding a [:managed-dependencies vector](https://github.com/technomancy/leiningen/blob/stable/doc/MANAGED_DEPS.md) to project.clj. Please add support for upgrading the dependency versions in this vector.

**Comment by nicorikken** [comment]
I worked around the issue by introducing a boot-clj wrapper project, which load the leiningen dependencies. Like https://github.com/ekroon/telehash-clj/blob/master/build.boot It would be better if the leiningen plugin supports `:managed-dependencies` though.

**Comment by xsc** [comment]
__[Release 0.6.12](https://github.com/xsc/lein-ancient/releases/tag/clojars-0.6.12)__
