### ISSUE TITLE
lein-ancient is not compatible with lein 2.8.0 (latest release)

### ISSUE THREAD

**Issue by tentamen** [xsc/lein-ancient#80]
As lein 2.8.0 remove clj-http and cheshire dependencies, so we got this exception when run `lein ancient`
```
clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate clj_http/client__init.class or clj_http/client.clj on classpath.
```

**Comment by xsc** [comment]
Ha, I can't even build it using Leiningen 2.8.0 (since another plugin we're using to isolate dependencies is no longer compatible, either).

Anyways, could you try the following?

```
[lein-ancient "0.6.13-SNAPSHOT"]
```

**Comment by ducky427** [comment]
@xsc, version `0.6.13-SNAPSHOT` works for me. Thanks!

**Comment by tentamen** [comment]
oh, current `0.6.13-SNAPSHOT` on master doesn't work for me, still got same issue with `clj-http` on Lein 2.8.0

**Comment by ducky427** [comment]
@tentamen, I downloaded the snapshot from clojars. Alternatively, could you try building from `fix/leiningen-2.8.0-compatibility` branch?

**Comment by tentamen** [comment]
ah, `0.6.13-SNAPSHOT` on clojars works fine! :+1:

**Comment by rborer** [comment]
I also confirm `0.6.13-SNAPSHOT` works fine for me :-)

**Comment by pmonks** [comment]
Also confirming that `0.6.13-SNAPSHOT` works for me here, on both JDK 1.8.0_131-b11 and JDK 9+181.  Nice work!  👍

**Comment by xsc** [comment]
__[Release Notes](https://github.com/xsc/lein-ancient/releases/tag/clojars-0.6.14)__
