### ISSUE TITLE
Incompatibility with Leiningen 2.8.1

### ISSUE THREAD

**Issue by xsc** [xsc/lein-ancient#86]
Issue extracted from [here](https://github.com/xsc/lein-ancient/issues/85#issuecomment-345328394):

> @ikitommi: After updating to to lein 2.8.1 ancient fails.

**Comment by ikitommi** [comment]
Hi, and sorry for the REALLY BAD description. After updating to lein 2.8.1, ancient failed but the after manually updating the version from `0.6.10` to `0.6.14` the problem got resolved.

**Comment by ikitommi** [comment]
This can be closed. And thanks for the awesome plugin!

**Comment by xsc** [comment]
Good to hear this is resolved! This seems to have been an instance of #80 and the plugin upgrade would have been my next recommendation. :)
