### ISSUE TITLE
lein ancient in ~/.lein to check profiles.clj

### ISSUE THREAD

**Issue by MrOerni** [xsc/lein-ancient#89]
It would be great if ancient worked in ~/.lein with existing profiles.clj

**Comment by xsc** [comment]
@MrOerni Let me know if the README is not clear enough on this, but there are the subtasks `check-profiles` and `upgrade-profiles` that should do what you want.

Hope that helps!

**Comment by MrOerni** [comment]
Oh... I should have read it more closely.

I just expected that `lein ancient` would work in `~/.lein`
